apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-kraft.clientServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "kafka-kraft.labels" . | nindent 4 }}
    app: kafka
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: kafka
    release: {{ .Release.Name }}
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
