apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-kraft.headlessServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "kafka-kraft.labels" . | nindent 4 }}
    app: kafka
    release: {{ .Release.Name }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: kafka
    release: {{ .Release.Name }}
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
